### ISSUE TITLE
Redirect downloads to IDM installed in linux with wine. 

### ISSUE THREAD

**Issue by a21-mohit** [belaviyo/download-with#1]
Is there possibility to redirect downloads to IDM (installed through wine) on linux?

**Comment by belaviyo** [comment]
Can you call the IDM from the command line?

**Comment by a21-mohit** [comment]
env WINEPREFIX="/home/mohit/.wine" /usr/bin/wine "C:\Program Files (x86)\Internet Download Manager\IDMan.exe"
Yeah with this command

**Comment by a21-mohit** [comment]
I tested . following thing works. the syntax is
       wine PROGRAM ARGUMENT
but env will be needed for per user. 

env WINEPREFIX="/home/mohit/.wine" /usr/bin/wine C:\Program\ Files\ \(x86\)\\Internet\ Download\ Manager\\IDMan.exe /d http://ipv4.download.thinkbroadband.com/100MB.zip

**Comment by a21-mohit** [comment]
~/.wine/drive_c/Program\ Files\ \(x86\)/Internet\ Download\ Manager/IDMan.exe /d "http://ipv4.download.thinkbroadband.com/100MB.zip"

This also works
