### ISSUE TITLE
Could we please have an option for autostart with JDownloader?

### ISSUE THREAD

**Issue by mageta** [belaviyo/download-with#17]
I think the relevant code is this:
https://github.com/belaviyo/download-with/blob/0a5b84da068edce4e774ba36f67dcba7a9f15be2/download-with-jdownloader/config.js#L51

Is it possible to make this adjustable by the configuration-gui? So that the links won't automatically start, but stay in the LinkGrabber till the user starts them.

**Comment by httan999** [comment]
I totally agree, but have you tried changing 1 to 0?

**Comment by mageta** [comment]
Tried it by quickly hard-coding a 0 there. Seems to work.

**Comment by httan999** [comment]
great, could you please tell me how?

**Comment by httan999** [comment]
nevermind, I figured it out, but once I change 1 to 0, the addons got corrupted and needs to be repaired, which undo my changes.

Is there another solution?

**Comment by belaviyo** [comment]
we will have a new option in the options page of the extension. Thanks for the report.
