### ISSUE TITLE
Doesn't work with Firefox but does with Chrome.

### ISSUE THREAD

**Issue by quietlystorming** [belaviyo/download-with#20]
Followed the install instructions but the check connection button still gives me "cannot find the native client" message on Firefox. %AppData%\Local\com.add0n.native_client and the files are there, even tried installing with admin privileges. Tried Chrome after and that works fine. I'm on Win8x64 using with JDownloader.

**Comment by simonbcn** [comment]
It also doesn't work with Firefox on Linux.

**Comment by simonbcn** [comment]
It also doesn't work with Firefox on Linux:
![captura_20190315_164337](https://user-images.githubusercontent.com/428231/54443742-84532a80-4741-11e9-93d9-3fba968e923d.png)

```
$ ll /home/juan/.config/com.add0n.native_client/
-rw-r--r-- 1 juan juan 3,0K mar 15 16:42 config.js
-rw-r--r-- 1 juan juan 1,8K mar 15 16:42 host.js
-rw-r--r-- 1 juan juan 3,5K mar 15 16:42 messaging.js
-rwxr-xr-x 1 juan juan   41 mar 15 16:42 run.sh

$ ll /home/juan/.mozilla/native-messaging-hosts/com.add0n.native_client.json 
-rw-r--r-- 1 juan juan 775 mar 15 16:42 /home/juan/.mozilla/native-messaging-hosts/com.add0n.native_client.json

```

**Comment by Grossdm** [comment]
> 
> 
> Followed the install instructions but the check connection button still gives me "cannot find the native client" message on Firefox. %AppData%\Local\com.add0n.native_client and the files are there, even tried installing with admin privileges. Tried Chrome after and that works fine. I'm on Win8x64 using with JDownloader.

I have the same problem.  There appears to be no interest from the @belaviyo .
Too bad for him; I donate to FOSS projects that don't suck.

**Comment by Grossdm** [comment]
The Firefox Browser Console has this output when you click the check connection button:

```
This extension does not have permission to use native manifest C:\Users\schultmc\AppData\Local\com.add0n.native_client\manifest-firefox.json NativeManifests.jsm:105
    _tryPath resource://gre/modules/NativeManifests.jsm:105
No such native application com.add0n.native_client NativeMessaging.jsm:99
    startupPromise resource://gre/modules/NativeMessaging.jsm:99
undefined index.js:47:11
    check moz-extension://9309819e-2a0e-4952-a1d4-3e3def914b73/data/guide/index.js:47
Unchecked lastError value: Error: Attempt to postMessage on disconnected port index.js:40
    check moz-extension://9309819e-2a0e-4952-a1d4-3e3def914b73/data/guide/index.js:40
```

**Comment by belaviyo** [comment]
Sorry for the late reply. Should have been fixed by `v0.4.2` release. https://github.com/belaviyo/native-client/releases/tag/v0.4.2

**Comment by hamoodNG** [comment]
# Visual Studio Test
# Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
- task: VSTest@2
  inputs:
    #testSelector: 'testAssemblies' # Options: testAssemblies, testPlan, testRun
    #testAssemblyVer2: | # Required when testSelector == TestAssemblies
    #  **\*test*.dll
    #  !**\*TestAdapter.dll
    #  !**\obj\** 
    #testPlan: # Required when testSelector == TestPlan
    #testSuite: # Required when testSelector == TestPlan
    #testConfiguration: # Required when testSelector == TestPlan
    #tcmTestRun: '$(test.RunId)' # Optional
    #searchFolder: '$(System.DefaultWorkingDirectory)' 
    #testFiltercriteria: # Optional
    #runOnlyImpactedTests: False # Optional
    #runAllTestsAfterXBuilds: '50' # Optional
    #uiTests: false # Optional
    #vstestLocationMethod: 'version' # Optional. Options: version, location
    #vsTestVersion: 'latest' # Optional. Options: latest, 16.0, 15.0, 14.0, toolsInstaller
    #vstestLocation: # Optional
    #runSettingsFile: # Optional
    #overrideTestrunParameters: # Optional
    #pathtoCustomTestAdapters: # Optional
    #runInParallel: False # Optional
    #runTestsInIsolation: False # Optional
    #codeCoverageEnabled: False # Optional
    #otherConsoleOptions: # Optional
    #distributionBatchType: 'basedOnTestCases' # Optional. Options: basedOnTestCases, basedOnExecutionTime, basedOnAssembly
    #batchingBasedOnAgentsOption: 'autoBatchSize' # Optional. Options: autoBatchSize, customBatchSize
    #customBatchSizeValue: '10' # Required when distributionBatchType == BasedOnTestCases && BatchingBasedOnAgentsOption == CustomBatchSize
    #batchingBasedOnExecutionTimeOption: 'autoBatchSize' # Optional. Options: autoBatchSize, customTimeBatchSize
    #customRunTimePerBatchValue: '60' # Required when distributionBatchType == BasedOnExecutionTime && BatchingBasedOnExecutionTimeOption == CustomTimeBatchSize
    #dontDistribute: False # Optional
    #testRunTitle: # Optional
    #platform: # Optional
    #configuration: # Optional
    #publishRunAttachments: true # Optional
    #diagnosticsEnabled: false # Optional
    #collectDumpOn: 'onAbortOnly' # Optional. Options: onAbortOnly, always, never
    #rerunFailedTests: False # Optional
    #rerunType: 'basedOnTestFailurePercentage' # Optional. Options: basedOnTestFailurePercentage, basedOnTestFailureCount
    #rerunFailedThreshold: '30' # Optional
    #rerunFailedTestCasesMaxLimit: '5' # Optional
    #rerunMaxAttempts: '3' # Optional

**Comment by hamoodNG** [comment]
> 
> # Visual Studio Test
> # Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
> 
>     * task: VSTest@2
>       inputs:
>       #testSelector: 'testAssemblies' # Options: testAssemblies, testPlan, testRun
>       #testAssemblyVer2: | # Required when testSelector == TestAssemblies
>       # *_*test_.dll
>       # !***TestAdapter.dll
>       # !**\obj**
>       #testPlan: # Required when testSelector == TestPlan
>       #testSuite: # Required when testSelector == TestPlan
>       #testConfiguration: # Required when testSelector == TestPlan
>       #tcmTestRun: '$(test.RunId)' # Optional
>       #searchFolder: '$(System.DefaultWorkingDirectory)'
>       #testFiltercriteria: # Optional
>       #runOnlyImpactedTests: False # Optional
>       #runAllTestsAfterXBuilds: '50' # Optional
>       #uiTests: false # Optional
>       #vstestLocationMethod: 'version' # Optional. Options: version, location
>       #vsTestVersion: 'latest' # Optional. Options: latest, 16.0, 15.0, 14.0, toolsInstaller
>       #vstestLocation: # Optional
>       #runSettingsFile: # Optional
>       #overrideTestrunParameters: # Optional
>       #pathtoCustomTestAdapters: # Optional
>       #runInParallel: False # Optional
>       #runTestsInIsolation: False # Optional
>       #codeCoverageEnabled: False # Optional
>       #otherConsoleOptions: # Optional
>       #distributionBatchType: 'basedOnTestCases' # Optional. Options: basedOnTestCases, basedOnExecutionTime, basedOnAssembly
>       #batchingBasedOnAgentsOption: 'autoBatchSize' # Optional. Options: autoBatchSize, customBatchSize
>       #customBatchSizeValue: '10' # Required when distributionBatchType == BasedOnTestCases && BatchingBasedOnAgentsOption == CustomBatchSize
>       #batchingBasedOnExecutionTimeOption: 'autoBatchSize' # Optional. Options: autoBatchSize, customTimeBatchSize
>       #customRunTimePerBatchValue: '60' # Required when distributionBatchType == BasedOnExecutionTime && BatchingBasedOnExecutionTimeOption == CustomTimeBatchSize
>       #dontDistribute: False # Optional
>       #testRunTitle: # Optional
>       #platform: # Optional
>       #configuration: # Optional
>       #publishRunAttachments: true # Optional
>       #diagnosticsEnabled: false # Optional
>       #collectDumpOn: 'onAbortOnly' # Optional. Options: onAbortOnly, always, never
>       #rerunFailedTests: False # Optional
>       #rerunType: 'basedOnTestFailurePercentage' # Optional. Options: basedOnTestFailurePercentage, basedOnTestFailureCount
>       #rerunFailedThreshold: '30' # Optional
>       #rerunFailedTestCasesMaxLimit: '5' # Optional
>       #rerunMaxAttempts: '3' # Optional
