### ISSUE TITLE
Feature request Send links to remote jdownloader

### ISSUE THREAD

**Issue by camousse** [belaviyo/download-with#21]
I use jdownloader with firefox, but the jdownloader is on a remote server. it would be nice to be able to send links to remote jdownloader. in doc, you said "check that localhost:9666 is accessible". so i think be able to change the "localhost" in plugin configuration would be enough. 
thanks

**Comment by rutervalfilho** [comment]
-----

**Comment by Cyberavater** [comment]
Use the official JD2 extension which I don't use for this specific feature.
https://chrome.google.com/webstore/detail/myjdownloader-browser-ext/fbcohnmimjicjdomonkcbcpbpnhggkip
