### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by marcelolaia** [belaviyo/download-with#22]
Wget saves the file in "./.config/com.add0n.native_client/"

How I could change the "./.config/com.add0n.native_client/" directory to "/home/$USER/Downloads"?

**Comment by zizodwa** [comment]
- [ ] @

**Comment by belaviyo** [comment]
```
-P prefix
--directory-prefix=prefix
           Set directory prefix to prefix.  The directory prefix is the
           directory where all other files and sub-directories will be
           saved to, i.e. the top of the retrieval tree.  The default
           is . (the current directory).
```
see https://stackoverflow.com/questions/1078524/how-to-specify-the-location-with-wget for more info

**Comment by marcelolaia** [comment]
I try:
-hold -e 'wget --directory-prefix="[/home/marcelo/Download/]" --output-document="[FILENAME]" --user-agent="[USERAGENT]" --referer="[REFERRER]" --no-check-certificate --continue --load-cookies=[COOKIES] "[URL]"'

-hold -e 'wget --directory-prefix="/home/marcelo/Download/" --output-document="[FILENAME]" --user-agent="[USERAGENT]" --referer="[REFERRER]" --no-check-certificate --continue --load-cookies=[COOKIES] "[URL]"'

and no working.

**Comment by belaviyo** [comment]
how about

```
-hold -e 'wget  --output-document="/home/marcelo/Download/[FILENAME]" --user-agent="[USERAGENT]" --referer="[REFERRER]" --no-check-certificate --continue --load-cookies=[COOKIES] "[URL]"'
```

**Comment by marcelolaia** [comment]
Yes! It do the job! Thanks!
