### ISSUE TITLE
Feature request: Download with .... (for selected text)

### ISSUE THREAD

**Issue by Cyberavater** [belaviyo/download-with#23]
I use JD2 and often there are links in a text which I select with the mouse and want to send them to JD2. JD2's official extension has this feature but I don't like its remote links sending feature so I don't use the official one. So please consider adding this feature.

P.S. I know there's already a feature called Download all with ... but it sends all links to the downloader I want only the selected links to be sent.

**Comment by shirbrenj** [comment]
echo "# alialavi" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/shirbrenj/alialavi.git
git push -u origin master

**Comment by belaviyo** [comment]
As of the next release, there will be a new context menu item to extract links from selection.

**Comment by Cyberavater** [comment]
@belaviyo Thanks! But even after clicking download, the prompt doesn't go away, which gives the impression that the links were not delivered to JD, where in reality link is successfully sent to JD.
