### ISSUE TITLE
Does it support non-English links?

### ISSUE THREAD

**Issue by HujiLee** [belaviyo/download-with#27]
I'm using `Download with Free Download Manager (FDM)`(version:0.1.7) in Opera(vesion : 62.0.3331.72).
When i try download this link for example:
```
https://qnm.hunliji.com/lrjQngNkycm09gKRvGMXB5h7jW0G?attname=%E6%97%A5%E8%AF%AD%E8%AF%AD%E6%B3%95%20%20%E9%99%88%E6%B4%81%E7%BE%BD%E4%B8%BB%E7%BC%96.pdf
```
in FDM window it becomes :
```
https://qnm.hunliji.com/lrjQngNkycm09gKRvGMXB5h7jW0G?attname=æ¥è¯­è¯­æ³  éæ´ç¾½ä¸»ç¼.pdf
```

![](http://m.tuniucdn.com/fb2/t1/G5/M00/0B/43/Cii-sl1RUs2ILO7KAAC6WccQbSsAAYudQOJBe0AALpx443.png)

OS : windows x64
Nodejs : v8.10.0
Native client:v0.4.2 (https://github.com/belaviyo/native-client/releases)

**Comment by belaviyo** [comment]
It will get fixed by the next release. Thanks for the report.
