### ISSUE TITLE
UTF-8 charachters in url

### ISSUE THREAD

**Issue by EhsanCh** [belaviyo/download-with#3]
Didn't handle utf8 characters in URL correctly

**Comment by belaviyo** [comment]
Example page?

**Comment by EhsanCh** [comment]
<a href="https://www.google.com/search?q=فارسی">test</a>

**Comment by HujiLee** [comment]
![80A7@FJIZHK 05H1}@LLH26](https://user-images.githubusercontent.com/18101185/62864285-dffc0100-bd3d-11e9-986d-5ae36cd73c6c.png)
sad..looks like it is still not fixed...

**Comment by belaviyo** [comment]
Will be fixed by the next release.
