### ISSUE TITLE
The save window comes out with FDM in the new Microsoft Edge

### ISSUE THREAD

**Issue by Xenon-Q** [belaviyo/download-with#34]
Hello.
I'm using this extention with Free Download Manager 3.9.7 (Which I think is far much better than 5.x and 6.x).
This is a nice extention, better than the official one of FDM. I'm using it in the new Microsoft Edge (Chromium based), but there is a trouble that when I click a download link, the save windows comes out with FDM, just like in Firefox, is this normal?

**Comment by belaviyo** [comment]
When enabled, the extension pauses the current download and sends it into the native application. If this process is successful, the extension removes the download from the list.

Have you changed the default dialog behavior:

![a](https://user-images.githubusercontent.com/1221138/85919844-71913600-b85e-11ea-9ecb-a6aad3d7779d.png)

**Comment by Xenon-Q** [comment]
> When enabled, the extension pauses the current download and sends it into the native application. If this process is successful, the extension removes the download from the list.
> 
> Have you changed the default dialog behavior:
> 
> ![a](https://user-images.githubusercontent.com/1221138/85919844-71913600-b85e-11ea-9ecb-a6aad3d7779d.png)

Yes, I set this option enabled before.
But I tried disable it just now, and FDM came out at the same time Edge started download that file

**Comment by belaviyo** [comment]
Please wait for the new release and reopen if it is not fixed.
