### ISSUE TITLE
Can't pass large links to Jdownloader still

### ISSUE THREAD

**Issue by Cyberavater** [belaviyo/download-with#36]
@belaviyo #29 is not fixed yet.

More example links;
1.
https://www.youtube.com/redirect?v=6uCMC02V6uQ&redir_token=QUFFLUhqbVRKa1JKVGhpdDVZaWlPOUc5YXdGSzdtckt0Z3xBQ3Jtc0tsbDBsSm5KMVppakxMZnlUSTk5cm9JUFRCeVQwZ1A2N3FiXzlJTmJiSWV3aXktc1pUenE3SklRRnJmRS1mMlVCc193UnJ6QlF5aDROdDZDVkw1MVdVekt6bWtrWTVWWk4tcGw1am5oN3F6UWZKT1FPTQ%3D%3D&event=video_description&q=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F16H02_V9QS13sh6uHsZ_LC6iLnv4d3ow4%2Fview%3Fusp%3Ddrivesdk

2.
https://www.youtube.com/redirect?event=video_description&v=_xU3wLImts0&redir_token=QUFFLUhqbWFDbkJfN1FFOGxJY1BlaHlUVzl0engyT0lkd3xBQ3Jtc0tsZXVCcWgwMFU4ZDBXTG5IQ0hlRENkOUJrbWhTal9aYVJBMUVhOTZYcFlrdHRIaXVKakNZa0FwN09WaUZXM0RsNVp0YkZZTDNCeUV3cGQ2QktXNkNwSWlBXzBrQWJqc2J5WXFMaFdmTmpsNTJoczRoVQ%3D%3D&q=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F14Yqy8dv1-qy4qs9XPOmdP8yYl7WCbg2D%2Fview%3Fusp%3Ddrivesdk

**Comment by belaviyo** [comment]
Thanks for the report. Try v0.2.2 release
