### ISSUE TITLE
Short filename option

### ISSUE THREAD

**Issue by Null-Kelvin** [belaviyo/download-with#4]
Firefox send in [FILENAME] full path to file, like "D:\Downloads\renamed.jpg" instead of just "renamed.jpg", so if I use "Download with IDM" with arguments /d "[URL]" /f "[FILENAME]", there be error. IDM try to save file "D:\Downloads\D:\Downloads\renamed.jpg"
For more flexibility I suggest to add option options [PATH] (D:\Downloads) and [SHORTNAME] (renamed.jpg)

**Comment by Mahdi1367** [comment]
https://github.com/Null-Kelvin
