### ISSUE TITLE
Default settings lead to wrong FDM path on Windows x64

### ISSUE THREAD

**Issue by lazyc97** [belaviyo/download-with#5]
On Windows x64, `%programfiles(x86)%` should be used instead of `%programfiles%`. There should be instructions for non-tech users.

**Comment by HujiLee** [comment]
![4R06U%0W$5J$15HJ5C6`Q15](https://user-images.githubusercontent.com/18101185/62864048-3ddc1900-bd3d-11e9-9267-ff5e2f3094c2.png)
you guess what,i installed a 32-bit FDM in my x64 windows...
