### ISSUE TITLE
What is the exclude syntax?

### ISSUE THREAD

**Issue by githwithit** [belaviyo/download-with#6]
I need to exclude files with the extension .torrent and have not been able to make the exclusion work along with the default exclusion for application/pdf. Thanks!

EDIT - this is for:
Win7-64, Firefox 57.0.4, FDM Free Download Manager 3.9.7-1638, native-client v0.3.7

**Comment by Karegohan-And-Kamehameha** [comment]
I encountered the same problem. By trial and error I found out that in order for exclusions to work they have to be separated by a comma. The MIME type for torrent files is "application/x-bittorrent". Names of other MIME types that have a program associated with them in Firefox and its forks can be found in the mimeTypes.rdf file located in your profile folder.

**Comment by githwithit** [comment]
@Karegohan-And-Kamehameha
Wonderful! Thanks, your feedback worked perfectly:
1) the exclusion delimiter is a comma - ","
2) the MIME type for torrent files is "application/x-bittorrent"
